# -*- coding: utf-8 -*-
"""project2pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLvLB6DLvwRk18vbXomGCMwcUMi3ezXk
"""

import logging
import os

# Define the log file path
log_file_path = 'colab_log.log'

# Remove existing log file if it exists to ensure a fresh log for each run
if os.path.exists(log_file_path):
    os.remove(log_file_path)

# Configure logging to a file
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_file_path)
    ]
)
logger = logging.getLogger(__name__)
logger.info('Logging setup complete. Messages will be written to colab_log.log')

import pandas as pd

try:
    data = pd.read_csv("virginia_air_quality_2024_2025_merged.csv")
    logger.info("Successfully loaded 'virginia_air_quality_2024_2025_merged.csv' into DataFrame.")
except FileNotFoundError:
    logger.error("Error: CSV file 'virginia_air_quality_2024_2025_merged.csv' not found. Please ensure the file is uploaded.")
    data = pd.DataFrame() # Initialize empty DataFrame to prevent further errors
except Exception as e:
    logger.error(f"An unexpected error occurred while loading the CSV: {e}")
    data = pd.DataFrame() # Initialize empty DataFrame

print(data.head())

len(data)

import sys
# Ensure pymongo is installed
!{sys.executable} -m pip install pymongo

from pymongo import MongoClient
from pymongo.errors import ConnectionFailure, OperationFailure

# MongoDB credentials are not included in this repository.
# Please see submission comments for the connection string.

# Replace with provided credentials
uri = "mongodb+srv://<username>:<password>@<cluster-url>/"

try:
    # Create MongoDB client
    client = MongoClient(uri)

    # Test connection
    client.admin.command('ping')
    print("Connected to MongoDB Atlas successfully!")

    # Access/create database
    db = client["air_quality"]

    # Access/create collection
    collection = db["virginia_data"]

    print("Database and collection ready.")

except ConnectionFailure as e:
    print(f"MongoDB connection failed: {e}")
except OperationFailure as e:
    print(f"MongoDB authentication or command failed: {e}")
except Exception as e:
    print(f"Unexpected error: {e}")

# Convert DataFrame to a list of dictionaries for MongoDB insertion
if 'data' in locals() and not data.empty:
    data_dict = data.to_dict(orient='records')
    try:
        # Insert the data into the collection
        insert_result = collection.insert_many(data_dict)
        logger.info(f"Inserted {len(insert_result.inserted_ids)} documents into the collection.")
        print(f"Inserted {len(insert_result.inserted_ids)} documents into the collection.")
    except OperationFailure as e:
        logger.error(f"MongoDB operation failed during data insertion: {e}")
        print(f"Error inserting data into MongoDB: {e}")
    except Exception as e:
        logger.error(f"An error occurred during data preparation/insertion to MongoDB: {e}")
        print(f"An error occurred during data insertion: {e}")
else:
    logger.warning("Data DataFrame is empty or not defined, skipping MongoDB insertion.")
    print("Data DataFrame is empty or not defined, skipping MongoDB insertion.")

# Define the target variable: (AQI > 50) Virginia has good air quality overall, wanted to make the threshold stricter so used AQI of 50 instead of 100
try:
    data['aqi_below_50'] = (data['aqi'] > 50).astype(int)
    logger.info("Target variable 'aqi_below_50' created successfully.")

    # Select features
    features = ['pm25', 'ozone', 'no2']
    X = data[features]
    y = data['aqi_below_50']
    logger.info("Features and target variable selected.")

    # Handle missing values in features (with mean)
    X = X.fillna(X.mean())
    logger.info("Missing values in features handled using mean imputation.")

    print("First 5 rows of features (X) after handling missing values:")
    display(X.head())
    print("First 5 values of target variable (y):")
    display(y.head())
except Exception as e:
    logger.error(f"Error during target variable definition or feature selection/handling: {e}")

from sklearn.model_selection import train_test_split

try:
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
    logger.info("Data split into training and testing sets successfully.")

    print(f"Shape of training features (X_train): {X_train.shape}")
    print(f"Shape of testing features (X_test): {X_test.shape}")
    print(f"Shape of training target (y_train): {y_train.shape}")
    print(f"Shape of testing target (y_test): {y_test.shape}")

    print("\nClass distribution in original target variable:")
    display(y.value_counts(normalize=True))
    print("\nClass distribution in training target variable:")
    display(y_train.value_counts(normalize=True))
    print("\nClass distribution in testing target variable:")
    display(y_test.value_counts(normalize=True))
except Exception as e:
    logger.error(f"Error during data splitting: {e}")

"""Using a Logistic Regression model for classification, as it's a good baseline for binary classification tasks, simple yet effective algorithm for predicting the probability of a binary outcome."""

from sklearn.linear_model import LogisticRegression

try:
    # Initialize the Logistic Regression model
    model = LogisticRegression(random_state=42, solver='liblinear') # 'liblinear' is a good choice for small datasets and binary classification
    logger.info("Logistic Regression model initialized.")

    # Train the model on the training data
    model.fit(X_train, y_train)
    logger.info("Logistic Regression model trained successfully!")

    print("Logistic Regression model trained successfully!")
except Exception as e:
    logger.error(f"Error during Logistic Regression model training: {e}")

"""Evaluating the trained model's performance on the test set using various metrics such as accuracy, precision, recall, F1-score, and the confusion matrix. These metrics will give a comprehensive understanding of how well the model predicts unhealthy air quality days."""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

try:
    # Make predictions on the test set
    y_pred = model.predict(X_test)
    logger.info("Predictions made on the test set.")

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    logger.info("Model evaluation metrics calculated.")

    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")

    # Display classification report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    # Plot Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
                xticklabels=['Predicted 0', 'Predicted 1'],
                yticklabels=['Actual 0', 'Actual 1'])
    plt.title('Confusion Matrix')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.show()
    logger.info("Confusion Matrix plotted and displayed.")
except Exception as e:
    logger.error(f"Error during model evaluation or plotting: {e}")

"""### Visualization Rationale: Confusion matrices are a crucial tool for evaluating the performance of a classification model, especially when dealing with imbalanced datasets. It provides a detailed breakdown of correct and incorrect predictions for each class. This visualization helped us understand the model's accuracy, precision, and recall in a more intuitive way than just looking at the numerical metrics, particularly highlighting how well the model identifies the positive class, or low quality air days.

For linear models like Logistic Regression, the coefficients of the features can be interpreted as their 'importance' or impact on the log-odds of the target variable. A positive coefficient indicates that as the feature value increases, the probability of a 'bad air day' increases. A negative coefficient indicates the opposite. The magnitude of the coefficient indicates the strength of this relationship.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

try:
    # Get the coefficients from the trained model
    coefficients = model.coef_[0]

    # Get the feature names
    feature_names = X.columns

    # Create a DataFrame for better visualization
    feature_importance = pd.DataFrame({'Feature': feature_names, 'Coefficient': coefficients})

    # Sort by absolute coefficient value for better readability
    feature_importance['Abs_Coefficient'] = feature_importance['Coefficient'].abs()
    feature_importance = feature_importance.sort_values(by='Abs_Coefficient', ascending=False)
    logger.info("Feature coefficients extracted and prepared for visualization.")

    plt.figure(figsize=(10, 6))
    sns.barplot(x='Coefficient', y='Feature', data=feature_importance, palette='viridis')
    plt.title('Logistic Regression Feature Coefficients')
    plt.xlabel('Coefficient Value')
    plt.ylabel('Feature')
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.show()
    logger.info("Feature coefficients plot displayed.")

    print("Feature Coefficients:")
    display(feature_importance[['Feature', 'Coefficient']])
except Exception as e:
    logger.error(f"Error during feature importance analysis or plotting: {e}")

"""### Visualization Rationale: The coefficients associated with each feature provide direct insights into the feature's importance and its impact on the target variable. Visualizing these coefficients makes their relative magnitudes and directions easier to understand. This visualization was key to understanding which pollutants were most influential in predicting unhealthy air quality days according to our model, with PM2.5 standing out as the strongest positive driver."""